global:
  scrape_interval: 1s
  evaluation_interval: 1s
  scrape_timeout: 1s

rule_files:
  - 'rules.local.yml'

scrape_configs:
  - job_name: 'polkadot-parachain-exporter'
    static_configs:
      - targets: ['exporter:8080']
