---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "$RELAYCHAIN-parachain-exporter-config"
data:
  PORT: "8080"
  WS_PROVIDER: "$WS_PROVIDER"
  PARACHAIN_IDS: "$PARACHAIN_IDS"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "$RELAYCHAIN-parachain-exporter"
  labels:
    app: "$RELAYCHAIN-parachain-exporter"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "$RELAYCHAIN-parachain-exporter"
  template:
    metadata:
      labels:
        app: "$RELAYCHAIN-parachain-exporter"
    spec:
      containers:
        - name: "$RELAYCHAIN-parachain-exporter"
          image: "$CONTAINER_REPO:$DOCKER_IMAGE_TAG"
          envFrom:
            - configMapRef:
                name: "$RELAYCHAIN-parachain-exporter-config"
          ports:
            - containerPort: 8080
              name: exporter
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "250m"
