---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '$RELAYCHAIN-parachain-exporter-monitor'
spec:
  selector:
    matchLabels:
      app: '$RELAYCHAIN-parachain-exporter'
  podMetricsEndpoints:
  - port: exporter
    interval: 45s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: parachain-alerting
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: parachain-exporter.rules
      rules:
        # This is just a dummy rule to make sure the PrometheusRule resource exists. It wil be replaced with the rules
        # in ../prometheus/rules.yml during deployment.
        - alert: RelayFinalizationPause
          expr: 'rate($METRICS_PREFIX_relaychain_finalized_head_number[5m]) <= bool 0'
          for: 20s
          labels:
            severity: critical
          annotations:
            summary: 'Finalized block on {{ $labels.chain }} has not increased for more than five minutes'
